import { columns } from "./columns";
import { DataTable } from "./table";

async function getData() {
  return [
    {
      id: "728ed52f",
      risk: "high",
      action: "block",
      dataClass: "Personal",
      file: "file.txt",
      user: "Alahi",
      destination: "USB",
      source: "C:\\",
      time: "2021-07-21 10:00:00",
    },
    {
      id: "728ed52f",
      risk: "low",
      action: "warn",
      dataClass: "Personal",
      file: "file.txt",
      user: "Fazle",
      destination: "USB",
      source: "C:\\",
      time: "2021-07-21 10:00:00",
    },
    {
      id: "728ed52f",
      risk: "medium",
      action: "log",
      dataClass: "Personal",
      file: "file.txt",
      user: "Alahi",
      destination: "USB",
      source: "C:\\",
      time: "2021-07-21 10:00:00",
    },
    {
      id: "728ed52f",
      risk: "high",
      action: "block",
      dataClass: "Personal",
      file: "file.txt",
      user: "Fazle",
      destination: "USB",
      source: "C:\\",
      time: "2021-07-21 10:00:00",
    },
    {
      id: "728ed52f",
      risk: "high",
      action: "block",
      dataClass: "Personal",
      file: "file.txt",
      user: "Alahi",
      destination: "USB",
      source: "C:\\",
      time: "2021-07-21 10:00:00",
    },
    {
      id: "728ed52f",
      risk: "high",
      action: "block",
      dataClass: "Personal",
      file: "file.txt",
      user: "Fazle",
      destination: "USB",
      source: "C:\\",
      time: "2021-07-21 10:00:00",
    },
    {
      id: "728ed52f",
      risk: "high",
      action: "block",
      dataClass: "Personal",
      file: "file.txt",
      user: "Alahi",
      destination: "USB",
      source: "C:\\",
      time: "2021-07-21 10:00:00",
    },
    {
      id: "728ed52f",
      risk: "high",
      action: "block",
      dataClass: "Personal",
      file: "file.txt",
      user: "Fazle",
      destination: "USB",
      source: "C:\\",
      time: "2021-07-21 10:00:00",
    },
    {
      id: "728ed52f",
      risk: "high",
      action: "block",
      dataClass: "Personal",
      file: "file.txt",
      user: "Alahi",
      destination: "USB",
      source: "C:\\",
      time: "2021-07-21 10:00:00",
    },
    {
      id: "728ed52f",
      risk: "high",
      action: "block",
      dataClass: "Personal",
      file: "file.txt",
      user: "Fazle",
      destination: "USB",
      source: "C:\\",
      time: "2021-07-21 10:00:00",
    },
    {
      id: "728ed52f",
      risk: "high",
      action: "block",
      dataClass: "Personal",
      file: "file.txt",
      user: "Alahi",
      destination: "USB",
      source: "C:\\",
      time: "2021-07-21 10:00:00",
    },
    {
      id: "728ed52f",
      risk: "high",
      action: "block",
      dataClass: "Personal",
      file: "file.txt",
      user: "Fazle",
      destination: "USB",
      source: "C:\\",
      time: "2021-07-21 10:00:00",
    },
    {
      id: "728ed52f",
      risk: "high",
      action: "block",
      dataClass: "Personal",
      file: "file.txt",
      user: "Alahi",
      destination: "USB",
      source: "C:\\",
      time: "2021-07-21 10:00:00",
    },
    {
      id: "728ed52f",
      risk: "high",
      action: "block",
      dataClass: "Personal",
      file: "file.txt",
      user: "Fazle",
      destination: "USB",
      source: "C:\\",
      time: "2021-07-21 10:00:00",
    },
    {
      id: "728ed52f",
      risk: "high",
      action: "block",
      dataClass: "Personal",
      file: "file.txt",
      user: "Alahi",
      destination: "USB",
      source: "C:\\",
      time: "2021-07-21 10:00:00",
    },
    {
      id: "728ed52f",
      risk: "high",
      action: "block",
      dataClass: "Personal",
      file: "file.txt",
      user: "Fazle",
      destination: "USB",
      source: "C:\\",
      time: "2021-07-21 10:00:00",
    },
    {
      id: "728ed52f",
      risk: "high",
      action: "block",
      dataClass: "Personal",
      file: "file.txt",
      user: "Alahi",
      destination: "USB",
      source: "C:\\",
      time: "2021-07-21 10:00:00",
    },
    {
      id: "728ed52f",
      risk: "high",
      action: "block",
      dataClass: "Personal",
      file: "file.txt",
      user: "Fazle",
      destination: "USB",
      source: "C:\\",
      time: "2021-07-21 10:00:00",
    },
  ];
}

export default async function Page() {
  const data = await getData();

  return (
    <div className="relative top-4 mx-10 mb-10 rounded-3xl bg-white p-4 pt-5 shadow-2xl">
      <h1 className="relative left-5 text-xl font-bold">Events Overview</h1>
      <DataTable columns={columns} data={data} />
    </div>
  );
}
